---
# tasks file for vector-role
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_0.33.0-1_amd64.deb"
    dest: "./{{ vector_version }}_amd64.deb"
    mode: 644
- name: Install package vector
  become: true
  ansible.builtin.apt:
    deb: "./{{ vector_version }}_amd64.deb"
    state: present

- name: Enable vector
  become: true
  ansible.builtin.systemd:
    name: vector.service
    enabled: true

- name: Start vector service
  become: true
  ansible.builtin.service:
    name: vector.service
    state: restarted
